ShoeShop/ShoeShop/Controllers/CategoiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShoeShop.Models;

namespace ShoeShop.Controllers
{
    public class CategoiesController : Controller
    {
        private ShoeDatabaseEntities dc;

        public ActionResult Index(int type)
        {
            dc = new ShoeDatabaseEntities();
            var model = dc.Types.Where(t => t.id == type).First();
            return View(model);
        }

        // GET: Categoies
        public ActionResult Category()
        {
            dc = new ShoeDatabaseEntities();
            var model = dc.Categories;

            var order = new Order();
            int? price = 0;
            if (User.Identity.IsAuthenticated)
            {
                User current_user = dc.Users.Where(c => c.username == User.Identity.Name).First();
                if (current_user.Orders.Count() > 0)
                    order = current_user.Orders.Last();
                else
                {
                    order = dc.Orders.Add(new Order() { userId = current_user.id, date = DateTime.Now });
                    dc.SaveChanges();
                }
                foreach (OrderDetail item in order.OrderDetails)
                {
                    Product product = dc.Products.Find(item.productId);
                    price += Convert.ToInt32(product.price) * item.quantity;
                };

            }
            OrderDetailTotal result = new OrderDetailTotal() { count = order.OrderDetails.Count(), total = price };

            ViewBag.result = result;
            return PartialView("_Header", model);
        }

        public ActionResult GetAllType()
        {
            dc = new ShoeDatabaseEntities();
            var model = dc.Categories;
            return PartialView("_Type", model);
        }

        public ActionResult GetAllBrand()
        {
            dc = new ShoeDatabaseEntities();
            var model = dc.Produces;
            return PartialView("_Brand", model);
        }

        public ActionResult ProductWithType(int type, int page = 1, int limit = 12)
        {
            dc = new ShoeDatabaseEntities();
            var model = dc.Products.Where(p => p.typeId == type);
            var productsPaging = model.OrderBy(p => p.name).Skip((page - 1) * limit).Take(limit);
            return PartialView("_ProductWithType", productsPaging);
        }
    }
}

ShoeShop/ShoeShop/Controllers/OrderController.cs
﻿using ShoeShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ShoeShop.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CheckOut()
        {
            ShoeDatabaseEntities db = new ShoeDatabaseEntities();
            User current_user = db.Users.Where(c => c.username == User.Identity.Name).First();
            var order = new Order();
            if (current_user.Orders.Count() > 0)
                order = current_user.Orders.Last();
            else
            {
                order = db.Orders.Add(new Order() { userId = current_user.id, date = DateTime.Now });
                db.SaveChanges();
            }
            int? price = 0;
            foreach (OrderDetail item in order.OrderDetails)
            {
                item.Size1 = db.Sizes.Find(item.size);
                item.Product = db.Products.Find(item.productId);
                price += Convert.ToInt32(item.Product.price) * item.quantity;
            };
            ViewBag.order_details = order.OrderDetails;
            ViewBag.total_price = price;
            ViewBag.delivery_charges = 150;
            ViewBag.orderID = order.id;
            ViewBag.number_record = order.OrderDetails.Count();
            return View();
        }
    }
}

ShoeShop/ShoeShop/Views/Shared/_Footer.cshtml
<div class="footer-grid">
    <div class="container">
        <div class="col-md-2 re-ft-grd">
            <h3>Categories</h3>
            <ul class="categories">
                <li><a href="#">Men</a></li>
                <li><a href="#">Women</a></li>
                <li><a href="#">Kids</a></li>
                <li><a href="#">Formal</a></li>
                <li><a href="#">Casuals</a></li>
                <li><a href="#">Sports</a></li>
            </ul>
        </div>
        <div class="col-md-2 re-ft-grd">
            <h3>Short links</h3>
            <ul class="shot-links">
                <li><a href="#">Contact us</a></li>
                <li><a href="#">Support</a></li>
                <li><a href="#">Delivery</a></li>
                <li><a href="#">Return Policy</a></li>
                <li><a href="#">Terms & conditions</a></li>
                <li><a href="contact.html">Sitemap</a></li>
            </ul>
        </div>
        <div class="col-md-6 re-ft-grd">
            <h3>Social</h3>
            <ul class="social">
                <li><a href="#" class="fb">facebook</a></li>
                <li><a href="#" class="twt">twitter</a></li>
                <li><a href="#" class="gpls">g+ plus</a></li>
                <div class="clearfix"></div>
            </ul>
        </div>
        <div class="col-md-2 re-ft-grd">
            <div class="bt-logo">
                <div class="logo pointer">
                    <a onclick="location.href = '@Url.Action("Index","Home")'">N-AIR</a>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="copy-rt">
        <div class="container">
            <p>&copy;   2015 N-AIR All Rights Reserved. Design by <a href="http://www.w3layouts.com">w3layouts</a></p>
        </div>
    </div>
</div>

ShoeShop/ShoeShop/Views/Shared/_Header.cshtml
@model IEnumerable<ShoeShop.Models.Category>
<script>
    $(document).ready(function () {
        $(".header .total_count_of_order").html($(".header #order_detail_count").val());
        $(".header .total_price_of_order").html("$ " + $(".header #order_detail_price").val());
    });

</script>
<div class="header">
    <div class="container">
        <div class="header-top">
            <div class="logo pointer">
                <a onclick="location.href = '@Url.Action("Index","Home")'" >N-AIR</a>
            </div>
            <div class="login-bars">
                @*<a class="btn btn-default log-bar" onclick="location.href= '@Url.Action("Login", "Account")'" role="button">Login</a>
                <a class="btn btn-default log-bar" onclick="location.href= '@Url.Action("Register", "Account")'" role="button">SignUp</a>*@
                @Html.Partial("_LoginPartial")
                <input id="order_detail_count" value=@ViewBag.result.count hidden>
                <input id="order_detail_price" value=@ViewBag.result.total hidden>
                <div class="cart box_1">
                    <a onclick="location.href= '@Url.Action("CheckOut", "Order")'">
                        <h3>
                            <div class="total pointer">
                                <span class="total_price_of_order">$ 0.00</span>(<span id="total_count_of_order" class="total_count_of_order">0</span>)
                            </div>
                        </h3>
                    </a>
                    <div class="clearfix"> </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        <!---menu-----bar--->
        <div class="header-botom">
            <div class="content white">
                <nav class="navbar navbar-default nav-menu" role="navigation">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="clearfix"></div>
                    <!--/.navbar-header-->

                    <div class="collapse navbar-collapse collapse-pdng" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav nav-font">
                            
                            <li><a href="#">Home</a></li>

                            @foreach (var category in Model)
                            {
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">@category.name<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        
                                        @foreach (var type in category.Types)
                                        {
                                            <li><a href='@Url.Action("Index", "Categoies", new { type = type.id})'>@type.name</a></li>
                                            @*<li class="divider"></li>*@   
                                        }

                                    </ul>
                                </li>
                            }
                            <li><a href="contact.html">Catch</a></li>
                            <div class="clearfix"></div>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <!--/.navbar-collapse-->
                    <div class="clearfix"></div>
                </nav>
                <!--/.navbar-->
                <div class="clearfix"></div>
            </div>
            <!--/.content--->
        </div>
        <!--header-bottom-->
    </div>
</div>

ShoeShop/ShoeShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>N-Air a E-commerce category Flat Bootstrap Responsive Website Template | Home :: w3layouts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="N-Air Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() {setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <meta charset utf="8">
    <!--fonts-->
    <link href='//fonts.googleapis.com/css?family=Fredoka+One' rel='stylesheet' type='text/css'>

    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")
    @RenderSection("scripts", required: false)
    <!--script-->
</head>
<body>
    
    @Html.Action("Category", "Categoies");

    @RenderBody()

    @Html.Partial("_Footer")

</body>
</html>