ShoeShop/ShoeShop/Controllers/CategoiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShoeShop.Models;

namespace ShoeShop.Controllers
{
    public class CategoiesController : Controller
    {
        private ShoeDatabaseEntities dc;

        public ActionResult Index(int type)
        {
            dc = new ShoeDatabaseEntities();
            var model = dc.Types.Where(t => t.id == type).First();
            return View(model);
        }

        // GET: Categoies
        public ActionResult Category()
        {
            dc = new ShoeDatabaseEntities();
            var model = dc.Categories;

            var order = new Order();
            int? price = 0;
            if (User.Identity.IsAuthenticated)
            {
                User current_user = dc.Users.Where(c => c.username == User.Identity.Name).First();
                if (current_user.Orders.Count() > 0)
                    order = current_user.Orders.Last();
                else
                {
                    order = dc.Orders.Add(new Order() { userId = current_user.id, date = DateTime.Now });
                    dc.SaveChanges();
                }
                foreach (OrderDetail item in order.OrderDetails)
                {
                    Product product = dc.Products.Find(item.productId);
                    price += Convert.ToInt32(product.price) * item.quantity;
                };

            }
            OrderDetailTotal result = new OrderDetailTotal() { count = order.OrderDetails.Count(), total = price };

            ViewBag.result = result;
            return PartialView("_Header", model);
        }

        public ActionResult GetAllType()
        {
            dc = new ShoeDatabaseEntities();
            var model = dc.Categories;
            return PartialView("_Type", model);
        }

        public ActionResult GetAllBrand()
        {
            dc = new ShoeDatabaseEntities();
            var model = dc.Produces;
            return PartialView("_Brand", model);
        }

        public ActionResult ProductWithType(int type, int page = 1, int limit = 12)
        {
            dc = new ShoeDatabaseEntities();
            var model = dc.Products.Where(p => p.typeId == type);
            var productsPaging = model.OrderBy(p => p.name).Skip((page - 1) * limit).Take(limit);
            return PartialView("_ProductWithType", productsPaging);
        }
    }
}

ShoeShop/ShoeShop/Controllers/ProductController.cs
﻿using ShoeShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ShoeShop.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ShoeDatabaseEntities db = new ShoeDatabaseEntities();
            Product item = db.Products.Find(id);
            ViewBag.Message = item;
            if (item == null)
            {
                return HttpNotFound();
            }
            var similar_item = db.Products.Where(c => c.typeId == item.typeId).ToList();
            ViewBag.Message2 = similar_item;

            var list_sizes = db.Sizes;
            ViewBag.list_sizes = list_sizes;
            return View();

        }
    }
}

ShoeShop/ShoeShop/Views/Categoies/Index.cshtml
@model ShoeShop.Models.Type

<!DOCTYPE html>
<html lang="en">
<head>
    <title>N-Air a E-commerce category Flat Bootstrap Responsive Website Template | Products :: w3layouts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="N-Air Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() {setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <meta charset utf="8">
    <!--fonts-->
    <link href='//fonts.googleapis.com/css?family=Fredoka+One' rel='stylesheet' type='text/css'>

    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")

    <link rel="stylesheet" href="css/flexslider.css" type="text/css" media="screen" />

    <script>
            // Can also be used with $(document).ready()
            $(window).load(function() {
              $('.flexslider').flexslider({
                animation: "slide",
                controlNav: "thumbnails"
              });
            });
    </script>
    <!-- //FlexSlider-->
</head>
<body>
   
    <div class="head-bread">
        <div class="container">
            <ol class="breadcrumb">
                <li><a href="index.html">Home</a></li>
                <li class="active" style="text-transform: uppercase;">@Model.Category.name</li>
                <li class="active" style="text-transform: uppercase;">@Model.name</li>
            </ol>
        </div>
    </div>

    <div class="products-gallery">
        <div class="container">
            <div id="productWithType">
                @Html.Action("ProductWithType", "Categoies", new { type = 0 })
            </div>

            <script type="text/javascript">
                $(document).ready(configController);

                var page = 1;
                var type = 0;

                function configController() {
                    $("#productWithType").load("@Url.Action("ProductWithType","Categoies")", { type: @Model.id })
                    type = @Model.id
                }

                function filterProductWithType(t) {
                    page = 1;
                    type = t;
                    $("#productWithType").load("@Url.Action("ProductWithType","Categoies")", { type: type });

                }

                function paginationProductWithType(value) {
                    var paging = page + value;
                    if (paging > 0) {
                        $("#productWithType").load("@Url.Action("ProductWithType","Categoies")", { type: type, page: paging });
                        page = paging;
                    }
                }

            </script>

            <div class="col-md-3 grid-details">
                <div class="grid-addon">
                    
                    <!---->
                    <link rel="stylesheet" type="text/css" href="css/jquery-ui.css">
                    @*<script type='text/javascript'>
                        //<![CDATA[
                        $(window).load(function () {
                            $("#slider-range").slider({
                                range: true,
                                min: 0,
                                max: 400000,
                                values: [2500, 350000],
                                slide: function (event, ui) {
                                    $("#amount").val("$" + ui.values[0] + " - $" + ui.values[1]);
                                }
                            });
                            $("#amount").val("$" + $("#slider-range").slider("values", 0) + " - $" + $("#slider-range").slider("values", 1));

                        });//]]>

                    </script>*@

                    <div class="clearfix"></div></div>
                    @Html.Action("GetAllType","Categoies")
                    <div class="clearfix"></div></div>
               
                    @*@Html.("ProductWithType", "Categoies", new { type = Model.id })*@
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    
</body>
</html>

ShoeShop/ShoeShop/Views/Categoies/_Brand.cshtml
@model IEnumerable<ShoeShop.Models.Produce>

<h4 class="m_2"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span>Categories</h4>
@foreach (var producer in Model)
{
    <ul class="place">
        <li class="sort" style="color: black; font-weight: bold;">@producer.name</li>
        <div class="clearfix"> </div>
    </ul>
}

ShoeShop/ShoeShop/Views/Categoies/_ProductWithType.cshtml
@model IEnumerable<ShoeShop.Models.Product>

<div class="col-md-9 grid-gallery">

    @foreach (var product in Model)
    {
        <div class="col-md-4 grid-stn simpleCart_shelfItem">
            <!-- normal -->
            <div class="ih-item square effect3 bottom_to_top">
                <div class="bottom-2-top">
                    <div class="img"><img src="~/Content/images/@product.image.Split(',')[2]" alt="/" class="img-responsive gri-wid"></div>
                    <div class="info">
                        <div class="pull-left">
                            <h3>@product.name</h3>
                        </div>
                        <div class="pull-right styl-price">
                            <p><a href="#" class="item_add"><span class="glyphicon glyphicon-shopping-cart grid-cart" aria-hidden="true"></span> <span class=" item_price">$@Math.Floor(product.price.Value)</span></a></p>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <!-- end normal -->
            <div class="quick-view pointer">
                <a href='@Url.Action("Index", "Product", new { id = @product.id })'>Quick view</a>
            </div>
        </div>
    }

    <div class="clearfix"></div>


    <nav aria-label="...">
        <ul class="pager">
            <li class="previous disabled"><a href="" onclick="paginationProductWithType(-1)"><span aria-hidden="true">&larr;</span> Older</a></li>
            <li class="next"><a href="" onclick="paginationProductWithType(1)">Newer <span aria-hidden="true">&rarr;</span></a></li>
        </ul>
    </nav>
</div>

ShoeShop/ShoeShop/Views/Categoies/_Type.cshtml
@model IEnumerable<ShoeShop.Models.Category>

<div class="clearfix"></div><section class="sky-form">
    <div class="product_right">
        <h4 class="m_2"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span>Categories</h4>

        @foreach (var category in Model)
        {
            <div class="tab-@category.id">
                <ul class="place">
                    <li class="sort">@category.name</li>
                    <li class="by"><img src="~/Content/images/do.png" alt=""></li>
                    <div class="clearfix"> </div>
                </ul>
                <div class="single-bottom">
                    @foreach (var type in category.Types)
                    {
                        <a href="#" onclick="filterProductWithType(@type.id)"><p>@type.name</p></a>
                    }
                    
                </div>
            </div>
        }

        <!--script-->

        @Html.Action("GetAllBrand", "Categoies")


        <script>
            $(document).ready(function () {
                $(".tab-1 .single-bottom").hide();
                $(".tab-2 .single-bottom").hide();
                $(".tab-3 .single-bottom").hide();
                $(".tab-4 .single-bottom").hide();
                $(".tab-5 .single-bottom").hide();

                $(".tab-1 ul").click(function () {
                    $(".tab-1 .single-bottom").slideToggle(300);
                    $(".tab-2 .single-bottom").hide();
                    $(".tab-3 .single-bottom").hide();
                    $(".tab-4 .single-bottom").hide();
                    $(".tab-5 .single-bottom").hide();
                })
                $(".tab-2 ul").click(function () {
                    $(".tab-2 .single-bottom").slideToggle(300);
                    $(".tab-1 .single-bottom").hide();
                    $(".tab-3 .single-bottom").hide();
                    $(".tab-4 .single-bottom").hide();
                    $(".tab-5 .single-bottom").hide();
                })
                $(".tab-3 ul").click(function () {
                    $(".tab-3 .single-bottom").slideToggle(300);
                    $(".tab-4 .single-bottom").hide();
                    $(".tab-5 .single-bottom").hide();
                    $(".tab-2 .single-bottom").hide();
                    $(".tab-1 .single-bottom").hide();
                })
                $(".tab-4 ul").click(function () {
                    $(".tab-4 .single-bottom").slideToggle(300);
                    $(".tab-5 .single-bottom").hide();
                    $(".tab-3 .single-bottom").hide();
                    $(".tab-2 .single-bottom").hide();
                    $(".tab-1 .single-bottom").hide();
                })
                $(".tab-5 ul").click(function () {
                    $(".tab-5 .single-bottom").slideToggle(300);
                    $(".tab-4 .single-bottom").hide();
                    $(".tab-3 .single-bottom").hide();
                    $(".tab-2 .single-bottom").hide();
                    $(".tab-1 .single-bottom").hide();
                })
            });
        </script>
        <!-- script -->


</section>