ShoeShop/ShoeShop/Models/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
        public string detail { get; set; }
        public Nullable<int> rating { get; set; }
        public string image { get; set; }
        public int produceId { get; set; }
        public int typeId { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Produce Produce { get; set; }
        public virtual Type Type { get; set; }
    }
}

ShoeShop/ShoeShop/Controllers/OrderDetailController.cs
﻿using ShoeShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ShoeShop.Controllers
{
    public class OrderDetailController : Controller
    {

        // GET: /OrderDetail/Create
        [HttpGet]
        public ActionResult Create(int product_id, int qty, int size)
        {
            try {
                ShoeDatabaseEntities db = new ShoeDatabaseEntities();
                User current_user = db.Users.Where(c => c.username == User.Identity.Name).First();
                var order = new Order();
                if (current_user.Orders.Count() > 0)
                    order = current_user.Orders.Last();
                else
                {
                    order = db.Orders.Add(new Order() { userId = current_user.id, date = DateTime.Now });
                    db.SaveChanges();
                }
                db.OrderDetails.Add(new OrderDetail() { orderId = order.id, productId = product_id, quantity = qty, size = 1 });
                db.SaveChanges();
            }
            catch (Exception e)
            {
                
            }
            
            return RedirectToAction("CheckOut", "Order");
        }

        [HttpPost]
        public ActionResult AddOrderDetail(int product_id, int qty, int size)
        {
            try
            {
                ShoeDatabaseEntities db = new ShoeDatabaseEntities();
                User current_user = db.Users.Where(c => c.username == User.Identity.Name).First();
                var order = new Order();
                if (current_user.Orders.Count() > 0)
                    order = current_user.Orders.Last();
                else
                {
                    order = db.Orders.Add(new Order() { userId = current_user.id, date = DateTime.Now });
                    db.SaveChanges();
                }
                db.OrderDetails.Add(new OrderDetail() { orderId = order.id, productId = product_id, quantity = qty, size = 1 });
                db.SaveChanges();
                int? price = 0;
                foreach (OrderDetail item in order.OrderDetails)
                {
                    Product product = db.Products.Find(item.productId);
                    price += Convert.ToInt32(product.price) * item.quantity;
                };

                OrderDetailTotal result = new OrderDetailTotal() { count = order.OrderDetails.Count(), total = price };

                return Json(result);
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(400, "Bad request");
            }
            
            
            
        }

        public ActionResult Remove(int? oId, int? pId)
        {
            ShoeDatabaseEntities db = new ShoeDatabaseEntities();
            OrderDetail od = db.OrderDetails.Where(c => c.orderId == oId && c.productId == pId).FirstOrDefault();
            db.OrderDetails.Remove(od);
            db.SaveChanges();
            return RedirectToAction("CheckOut", "Order");
        }

        public ActionResult PlacOrder(int? id)
        {
            ShoeDatabaseEntities db = new ShoeDatabaseEntities();
            Order order = db.Orders.Find(id);

            db.OrderDetails.RemoveRange(order.OrderDetails);
            db.SaveChanges();
            return RedirectToAction("CheckOut", "Order");
        }
    }
}

ShoeShop/ShoeShop/Controllers/ProductController.cs
﻿using ShoeShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ShoeShop.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ShoeDatabaseEntities db = new ShoeDatabaseEntities();
            Product item = db.Products.Find(id);
            ViewBag.Message = item;
            if (item == null)
            {
                return HttpNotFound();
            }
            var similar_item = db.Products.Where(c => c.typeId == item.typeId).ToList();
            ViewBag.Message2 = similar_item;

            var list_sizes = db.Sizes;
            ViewBag.list_sizes = list_sizes;
            return View();

        }
    }
}

ShoeShop/ShoeShop/Views/Product/Index.cshtml
@model ShoeShop.Models.Product

@{
    ViewBag.Title = "Index";
}

<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html lang="en">
<head>
    <title>N-Air a E-commerce category Flat Bootstrap Responsive Website Template | Single :: w3layouts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="N-Air Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() {setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <meta charset utf="8">
    <!--fonts-->
    <link href='//fonts.googleapis.com/css?family=Fredoka+One' rel='stylesheet' type='text/css'>

    <!--fonts-->
    <!--bootstrap-->
    <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <!--coustom css-->
    <link href="css/style.css" rel="stylesheet" type="text/css" />
    <!--shop-kart-js-->
    <script src="js/simpleCart.min.js"></script>
    <!--default-js-->
    <script src="js/jquery-2.1.4.min.js"></script>
    <!--bootstrap-js-->
    <script src="js/bootstrap.min.js"></script>
    <!--script-->
    <!-- FlexSlider -->
    <script src="js/imagezoom.js"></script>
    <script defer src="js/jquery.flexslider.js"></script>


    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="~/Content/css/flexslider.css" type="text/css" media="screen" />
    <style>
        .flex-viewport {
            max-height: 750px !important;
        }
    </style>
    <script>
        // Can also be used with $(document).ready()
        $(window).load(function () {
            $('.flexslider').flexslider({
                animation: "slide",
                controlNav: "thumbnails"
            });
        });
    </script>
    <!-- //FlexSlider-->
</head>
<body>


    <div class="head-bread">
        <div class="container">
            <ol class="breadcrumb">
                <li><a onclick="location.href = '@Url.Action("Index","Home")'">Home</a></li>
                <li><a href="#">Men</a></li>
                <li class="active">Shop</li>
            </ol>
        </div>
    </div>
    <div class="showcase-grid">
        <div class="container">
            <div class="col-md-8 showcase">

                <div class="flexslider">
                    <ul class="slides">
                        @foreach (var image in ViewBag.Message.image.Split(','))
                        {
                            <li data-thumb="/Content/images/@image">
                                <div class="thumb-image"> <img style="width: 100%; height: 100%;" src="~/Content/images/@image" class="img-responsive" data-imagezoom="true" />  </div>
                            </li>

                        }
                        <!-- items mirrored twice, total of 12 -->
                    </ul>
                </div>

            </div>
            <div class="col-md-4 showcase">
                <div class="showcase-rt-top">
                    <div class="pull-left shoe-name">
                        <h3>@ViewBag.Message.name</h3>
                        <p>@ViewBag.Message.Type.name</p>
                        <h4>VND @ViewBag.Message.price</h4>
                    </div>
                    <input id="product-id" value=@ViewBag.Message.id hidden >
                    <div class="pull-left rating-stars">
                        <ul>                            
                            @for (int i = 1; i <= ViewBag.Message.rating; i++)
                            {
                                <li><a href="#" class="active"><span class="glyphicon glyphicon-star star-stn" aria-hidden="true"></span></a></li>                          
                            }
                            @for (int i = 1; i <= (5 - ViewBag.Message.rating); i++)
                            {
                                <li><a href="#"><span class="glyphicon glyphicon-star star-stn" aria-hidden="true"></span></a></li>
                            }
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <hr class="featurette-divider">
                <div class="shocase-rt-bot">
                    <div class="float-qty-chart">
                        <ul>
                            <li class="qty">
                                <h3>Size Chart</h3>
                                <select class="form-control siz-chrt">
                                    @foreach (var size in ViewBag.list_sizes)
                                    {
                                        <option value=@size.id>@size.name</option>
                                    } 
                                </select>
                            </li>
                            <li class="qty">
                                <h4>QTY</h4>
                                <select class="form-control qnty-chrt">
                                    <option>1</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                    <option>5</option>
                                    <option>6</option>
                                    <option>7</option>
                                </select>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <ul>
                        <li class="ad-2-crt simpleCart_shelfItem">
                            <a class="btn item_add btn-add-to-cart" href="#" role="button">Add To Cart</a>
                            <a class="btn btn-buynow" role="button">Buy Now</a>
                        </li>
                    </ul>
                </div>
                <div class="showcase-last">
                    <h3>product details</h3>
                    @*<ul>
                        <li>Internal bootie wraps your foot for a sock-like fit</li>
                        <li>Unique eyestays work with the Flywire cables to create an even better glove-like fit</li>
                        <li>Waffle outsole for durability and multi-surface traction</li>
                        <li>Sculpted Cushlon midsole combines plush cushioning and springy resilience for impact protection</li>
                        <li>Midsole flex grooves for greater forefoot flexibility</li>
                    </ul>*@
                    <li>@ViewBag.Message.detail</li>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="specifications">
        <div class="container">
            <h3>Item Details</h3>
            <div class="detai-tabs">
                <!-- Nav tabs -->
                <ul class="nav nav-pills tab-nike" role="tablist">
                    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Highlights</a></li>
                    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Description</a></li>
                    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Terms & conditiona</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="home">
                        <p>The full-length Max Air unit delivers excellent cushioning with enhanced flexibility for smoother transitions through footstrike.</p>
                        <p>Dynamic Flywire cables integrate with the laces and wrap your midfoot for a truly adaptive, supportive fit.</p>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="profile">
                        <p>Nike is one of the leading manufacturer and supplier of sports equipment, footwear and apparels. Nike is a global brand and it continuously creates products using high technology and design innovation. Nike has a vast collection of sports shoes for men at Snapdeal. You can explore our range of basketball shoes, football shoes, cricket shoes, tennis shoes, running shoes, daily shoes or lifestyle shoes. Take your pick from an array of sports shoes in vibrant colours like red, yellow, green, blue, brown, black, grey, olive, pink, beige and white. Designed for top performance, these shoes match the way you play or run. Available in materials like leather, canvas, suede leather, faux leather, mesh etc, these shoes are lightweight, comfortable, sturdy and extremely sporty. The sole of all Nike shoes is designed to provide an increased amount of comfort and the material is good enough to provide an improved fit. These shoes are easy to maintain and last for a really long time given to their durability. Buy Nike shoes for men online with us at some unbelievable discounts and great prices. So get faster and run farther with your Nike shoes and track how hard you can play.</p>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="messages">
                        The images represent actual product though color of the image and product may slightly differ.
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="you-might-like">
        <div class="container">
            <h3 class="you-might">Products You May Like</h3>
            @foreach (var item in ViewBag.Message2)
            {
                <div class="col-md-4 grid-stn simpleCart_shelfItem">
                    <!-- normal -->
                    <div class="ih-item square effect3 bottom_to_top">
                        <div class="bottom-2-top">
                            <div class="img"><img src="~/Content/images/@item.image.Split(',')[0]" alt="/" class="img-responsive gri-wid"></div>
                            <div class="info">
                                <div class="pull-left styl-hdn">
                                    <h3>@item.name</h3>
                                </div>
                                <div class="pull-right styl-price">
                                    <p><a href="#" class="item_add"><span class="glyphicon glyphicon-shopping-cart grid-cart" aria-hidden="true"></span> <span class=" item_price">$@item.price</span></a></p>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                    <!-- end normal -->
                    <div class="quick-view pointer">
                        <a onclick="location.href= '@Url.Action("Index", "Product", new { id=@item.id })'">View Details</a>
                    </div>
            </div>    
            }

            <div class="clearfix"></div>
        </div>
    </div>
    <script>
    // Can also be used with $(document).ready()
        $(".btn-buynow").on("click", function () {
            $(this).attr("href", '@Url.Action("Create", "OrderDetail", new { product_id=ViewBag.Message.id})' + "&&qty=" + $('.qnty-chrt').val() + "&&size=" + $('.siz-chrt').val());
        });
        $(".btn-add-to-cart").on("click", function () {
            var string = {
                product_id: $('#product-id').val(),
                qty: $('.qnty-chrt').val(),
                size: $('.siz-chrt').val()
            }
            $.ajax({
                url: '@Url.Action("AddOrderDetail", "OrderDetail", new { product_id=ViewBag.Message.id})' + "&&qty=" + $('.qnty-chrt').val() + "&&size=" + $('.siz-chrt').val(),
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: null,
                success: function (result) {
                    $("body .total_price_of_order").html("$ " + result.total);
                    $("body .total_count_of_order").html(result.count);
                    alert("Success");
                },
                error: function (result) {
                    alert("Aw, you are already add this product to cart");
                }
            });
            return false;
        });
    </script>

</body>
</html>